#!/bin/bash

echo -n "site: "
read site
echo -n "domain: "
read domain

echo "site entered: $site"
echo "domain entered: $domain"
echo "downloading website..."

wget --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains $domain \
     --no-parent \
     $site

echo "site downloaded!"
